version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-persistente
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: palestra_test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
