version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password  # Senha do usuário root
      MYSQL_DATABASE: devweb         # Banco de dados inicial
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0  # Permite conexões externas
    networks:
      - app-network

  php:
    build:
      context: ./php
    container_name: php_container
    volumes:
      - ./html:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge